/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CekilisUygulaması;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Random;
import java.util.Scanner;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emre
 */
public class MainFrame extends javax.swing.JFrame {

    public static int no = 1;
    public MainFrame() {
        initComponents();
        // initComponents çağrısından sonra model oluşturulmalı
        DefaultTableModel model = (DefaultTableModel) tblKisiler.getModel();
        try {
            ArrayList<String> kisiler = getKisiler();
            for (String kisi : kisiler) {
                Object[] row = {no, kisi};
                no++;
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public ArrayList<String> getKisiler() throws FileNotFoundException {
        String yol = "C:/Users/Emre/Documents/NetBeansProjects/CekilisUygulamasi/src/main/java/CekilisUygulaması/Kisiler.txt";
        File file = new File(yol);
        Scanner scanner = new Scanner(file);
        ArrayList<String> kisiler = new ArrayList<>(); // ArrayList başlatıldı
        try {
            while (scanner.hasNextLine()) {
                String kisi = scanner.nextLine();
                kisiler.add(kisi);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return kisiler;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCekilis = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKisiler = new javax.swing.JTable();
        lblGösterge = new javax.swing.JLabel();
        lblKazananlar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Çekiliş İçin Tıklayın");

        btnCekilis.setText("Çekiliş Yap");
        btnCekilis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekilisActionPerformed(evt);
            }
        });

        tblKisiler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "İsim Soyisim"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblKisiler);
        if (tblKisiler.getColumnModel().getColumnCount() > 0) {
            tblKisiler.getColumnModel().getColumn(0).setMinWidth(40);
            tblKisiler.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblKisiler.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        lblGösterge.setText("Kazanan Kişiler: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCekilis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblGösterge)
                                .addGap(18, 18, 18)
                                .addComponent(lblKazananlar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(13, 13, 13))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCekilis)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGösterge)
                    .addComponent(lblKazananlar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCekilisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekilisActionPerformed
         Random random = new Random();
        DefaultTableModel model = (DefaultTableModel) tblKisiler.getModel();
        int rowCount = model.getRowCount();
        Set<Integer> kazananIndeksler = new HashSet<>();
        StringBuilder kazananlar = new StringBuilder();

        while (kazananIndeksler.size() < 3 && kazananIndeksler.size() < rowCount) {
            int tercih = random.nextInt(rowCount);
            if (!kazananIndeksler.contains(tercih)) {
                kazananIndeksler.add(tercih);
                String kazanan = (String) model.getValueAt(tercih, 1);
                kazananlar.append(kazanan).append(", ");
            }
        }
        
        lblKazananlar.setText(kazananlar.toString());
        lblGösterge.setVisible(true);
        lblKazananlar.setVisible(true);
    }//GEN-LAST:event_btnCekilisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCekilis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGösterge;
    private javax.swing.JLabel lblKazananlar;
    private javax.swing.JTable tblKisiler;
    // End of variables declaration//GEN-END:variables
}
